const images = {
    headerHome: require('./headerhome.png'),
    history: require('./history.gif'),
    contabilidad: require('./contabilidad.png'),
    produccion: require('./produccion.png'),
    ventas: require('./ventas.png'),
    sistemas: require('./sistemas.png'),
    diseno: require('./diseno.png'),
    admin: require('./admin.png'),
    mercadeo: require('./mercadeo.png'),
    carrito: require('./carrito.png'),
    contacto: require('./contacto.png'),
    tiendas: require('./tiendas.png'),
    twitter: require('./twitter.png'),
    facebook: require('./facebook.png'),
    instagram: require('./instagram.png'),
    rrhh: require('./rrhh.png'),
    produccion: require('./produccion.png'),
    ventas: require('./ventas.png'),
    todos : require('./todos.png'),
    cremaLeche: require('./cremadeleche.png'),
    cremaEspecias: require('./cremaespecias.png'),
    jugoNaranja: require('./jugonaranja.png'),
    mantequilla: require('./mantequilla.png'),
    ricotta: require('./ricotta.png'),
    nectarDurazno: require('./nectardurazno.png'),
    nectarManzana: require('./nectarmanzana.png'),
    nectarPera: require('./nectarpera.png'),
    quesoMozarella: require('./quesomozarella.png'),
    suero: require('./suero.png'),
  }
  
  export default images
  